INSERT INTO blockchain
    (nome, simbolo, algoritmo_consenso, rede_principal)
VALUES
    ('Bitcoin', 'BTC', 'Proof of Work', 'Mainnet'),
    ('Ethereum', 'ETH', 'Proof of Stake', 'Mainnet'),
    ('BNB Chain', 'BNB', 'Proof of Staked Authority', 'Mainnet'),
    ('Solana', 'SOL', 'Proof of Stake', 'Mainnet'),
    ('Cardano', 'ADA', 'Ouroboros Proof of Stake', 'Mainnet'),
    ('XRP Ledger', 'XRP', 'Federated Consensus', 'Mainnet'),
    ('Avalanche', 'AVAX', 'Proof of Stake', 'Mainnet'),
    ('Polkadot', 'DOT', 'Nominated Proof of Stake', 'Mainnet'),
    ('TRON', 'TRX', 'Delegated Proof of Stake', 'Mainnet'),
    ('Cosmos Hub', 'ATOM', 'Tendermint BFT', 'Mainnet'),
    ('Litecoin', 'LTC', 'Proof of Work', 'Mainnet'),
    ('Dogecoin', 'DOGE', 'Proof of Work', 'Mainnet'),
    ('Bitcoin Cash', 'BCH', 'Proof of Work', 'Mainnet'),
    ('Stellar', 'XLM', 'Stellar Consensus Protocol', 'Mainnet'),
    ('Algorand', 'ALGO', 'Pure Proof of Stake', 'Mainnet'),
    ('NEAR Protocol', 'NEAR', 'Nightshade Proof of Stake', 'Mainnet'),
    ('Internet Computer', 'ICP', 'Threshold Relay', 'Mainnet'),
    ('Fantom', 'FTM', 'Lachesis', 'Mainnet'),
    ('Hedera', 'HBAR', 'Hashgraph Consensus', 'Mainnet'),
    ('Tezos', 'XTZ', 'Liquid Proof of Stake', 'Mainnet'),
    ('Monero', 'XMR', 'Proof of Work', 'Mainnet'),
    ('EOS', 'EOS', 'Delegated Proof of Stake', 'Mainnet'),
    ('Arbitrum One', 'ARB', 'Proof of Stake', 'Mainnet'),
    ('Optimism', 'OP', 'Proof of Stake', 'Mainnet'),
    ('Polygon PoS', 'POL', 'Proof of Stake', 'Mainnet'),
    ('Aptos', 'APT', 'Proof of Stake', 'Mainnet'),
    ('Sui', 'SUI', 'Delegated Proof of Stake', 'Mainnet'),
    ('Injective', 'INJ', 'Tendermint Proof of Stake', 'Mainnet'),
    ('Celestia', 'TIA', 'Proof of Stake', 'Mainnet'),
    ('Cronos', 'CRO', 'Tendermint Proof of Stake', 'Mainnet'),
    ('Kaspa', 'KAS', 'Proof of Work', 'Mainnet'),
    ('VeChain', 'VET', 'Proof of Authority', 'Mainnet'),
    ('Theta Network', 'THETA', 'Proof of Stake', 'Mainnet'),
    ('Flow', 'FLOW', 'Proof of Stake', 'Mainnet'),
    ('Elrond', 'EGLD', 'Secure Proof of Stake', 'Mainnet'),
    ('MultiversX', 'EGLD', 'Secure Proof of Stake', 'Mainnet'),
    ('Kava', 'KAVA', 'Tendermint Proof of Stake', 'Mainnet'),
    ('Harmony', 'ONE', 'Effective Proof of Stake', 'Mainnet'),
    ('Zilliqa', 'ZIL', 'Practical Byzantine Fault Tolerance', 'Mainnet'),
    ('Conflux', 'CFX', 'Tree-Graph Proof of Work', 'Mainnet'),
    ('IOTA', 'IOTA', 'Tangle Consensus', 'Mainnet'),
    ('Kusama', 'KSM', 'Nominated Proof of Stake', 'Mainnet'),
    ('Ronin', 'RON', 'Proof of Stake', 'Mainnet'),
    ('Moonbeam', 'GLMR', 'Proof of Stake', 'Mainnet'),
    ('Celo', 'CELO', 'Proof of Stake', 'Mainnet'),
    ('Osmosis', 'OSMO', 'Tendermint Proof of Stake', 'Mainnet'),
    ('THORChain', 'RUNE', 'Proof of Stake', 'Mainnet'),
    ('Stacks', 'STX', 'Proof of Transfer', 'Mainnet'),
    ('Waves', 'WAVES', 'Leased Proof of Stake', 'Mainnet'),
    ('Qtum', 'QTUM', 'Proof of Stake', 'Mainnet');